### ISSUE TITLE
fails for Safari <14 iPhone <7

### ISSUE THREAD

**Issue by dohomi** [ihordiachenko/supports-webp-sync#1]
Hi,

your browser check fails for Safari < 14

Cheers

**Comment by ihordiachenko** [comment]
Hi @dohomi 

Do you get a false positive for Safari < 14?

**Comment by dohomi** [comment]
@ihordiachenko yes, all iPhones < 7 (safari 13.x) will get a false positive

**Comment by ihordiachenko** [comment]
@dohomi couldn't reproduce it in XCode emulator and browserstack. Could you make a screenshot of this page?
https://ihordiachenko.github.io/supports-webp-sync/

**Comment by dohomi** [comment]
@ihordiachenko this is the screenshot seems not to be a false positive but still I couldn't use the lib
![WhatsApp Image 2021-05-11 at 22 49 16](https://user-images.githubusercontent.com/489221/117904249-96ba5600-b303-11eb-9138-dd33458a9887.jpeg)

**Comment by ihordiachenko** [comment]
@dohomi the result on the screenshot is correct, WebP support was introduced only in Safari 14:
https://caniuse.com/?search=webp

Could you elaborate what the problem was?

**Comment by dohomi** [comment]
In NextJS I received a false positiv and all images would not work at all. I replaced it now with server side code and will close the issue.

**Comment by ihordiachenko** [comment]
@dohomi thank you for the clarifications. Just to be sure, was the check executed on server side?

**Comment by dohomi** [comment]
@ihordiachenko client side only
